services:

  rust_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rust
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/app/.env:ro
      - ./db/:/app/db/
    restart: unless-stopped
